webmvc:
  cors:
    allowed-origins: "https://mine.codeyzer.com" # Frontend'in çalıştığı adres (tırnak içinde olması daha güvenli)
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS
    allowed-headers: '*'
    allow-credentials: true # WebSocket/Cookie gerekiyorsa
logging:
  level:
    com.codeyzer.mine: WARN # Üretim ortamında sadece uyarı ve hataları logla
