# Ortak Ayarlar (Tüm profiller için geçerli)
server:
  port: 8080

spring:
  profiles:
    active: dev # Varsayılan olarak dev profili aktif olsun
  mvc:
    async:
      request-timeout: 30s # Genel istek zaman aşımı

